### PR TITLE
Biggulped

### PR DESCRIPTION
**Pull request by ianevatt**
node-hilo has been assimilated.

image

changed file/folder structure to more closely resemble existing node projects and implemented biggulp. 

@ifandelse added the linting and formatting gulp tasks back in until we can get that into biggulp
@arobson did i node it right???

### CODE REVIEW

**Comment by ifandelse** [comment]
will try and review today :smile:

**Comment by rniemeyer** [comment]
I reviewed this one. Looks good to me, other than that I think it was preferable to have the jshint/formatting tasks running by default (as dependencies of the main tasks).

**Comment by ifandelse** [comment]
@ianevatt & @arobson  - I agree with @rniemeyer, ideally we need them run by default.

**Comment by rniemeyer** [comment]
We should sync up the npm scripts section as well, as one refers to `gulp test` that no longer exists.

**Comment by ianevatt** [comment]
im pretty sure i addressed all of the concerns you guys had with this latest commit. I also went ahead and changed the task verbiage to 'test' everywhere instead of 'spec' or 'specs' which was a little messy. went back and forth on whether or not to make that a separate commit... then didnt :smile: 

the `npm test` command will now work as expected and istanbul coverage reports will use gulp tasks and are no longer a part of the scripts. 

the default gulp task now includes the formatting/linting steps as well

**Comment by rniemeyer** [comment]
@ianevatt - because the format task writes the files in place, we likely want to be careful with other tasks running in parallel. Probably would be okay to add `format` as a dependency to `coverage` and `jshint` is already a dependency of `format`.

**Comment by ianevatt** [comment]
@rniemeyer i think that does it. thanks for the feedback

**Pull request merged**
